export const ADMIN_CONTACT_PHONE_DISPLAY =
  process.env.NEXT_PUBLIC_ADMIN_CONTACT_PHONE_DISPLAY?.trim() || '0474 576 085'

export const ADMIN_CONTACT_PHONE_TEL =
  process.env.NEXT_PUBLIC_ADMIN_CONTACT_PHONE_TEL?.trim() || '+61474576085'
